[package]
name = "pancake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
derive_more = "*"
hyper = { version = "*", features = ["full"] }
itertools = "*"
num-derive = "0.3"
num-traits = "0.2"
regex = "*"
routerify = "*"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
rand = "*"
rusty-hook = "^0.11.0"
