[package]
name = "pancake"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
derive_more = "*"
futures = "*"
hyper = { version = "*", features = ["full"] }
itertools = "*"
routerify = "*"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
rand = "*"
