name: Rustdoc to Github Pages

on:
  push:
    branches:
      - ysono/doc

env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc-ghpages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo doc --no-deps
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
